# =========================================
# Configuracion de la base de datos (MySQL)
# En Railway estas variables se inyectan automaticamente
# si defines la variable de entorno con esos nombres exactos
# apuntando a las que crea el plugin de MySQL de Railway.
# =========================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/tienda_inventario}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Puerto (Railway inyecta PORT automaticamente)
server.port=${PORT:8080}

# JWT
app.jwt.secret=${JWT_SECRET:cambia-esta-clave-por-una-muy-larga-y-secreta-en-produccion-1234567890}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# Tasa de cambio (API externa)
app.exchangerate.api-url=${EXCHANGE_API_URL:https://api.exchangerate-api.com/v4/latest/USD}
app.exchangerate.moneda-base=${MONEDA_BASE:USD}

# Nombre app
spring.application.name=inventario

# Manejo de errores mas limpio
server.error.include-message=always
server.error.include-binding-errors=always
